name: Trevor Pfahl
favicon: null
layout_spectrum: 0.8072162023745477
typography_spectrum: 0.06450091674923897
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.13727226480841637
  lightness: 0.960997999412939
  saturation: 0.5662255263887346
  rhythmicContrast: 0.2676744007039815
purpose: []
